plugins:
  - rubocop-zuno
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3

Naming/FileName:
  Exclude:
    - "lib/rubocop-zuno.rb"

Rails/RakeEnvironment:
  Enabled: false
