name: CI

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073
        with:
          bundler-cache: true
      - run: bundle exec rubocop
      - run: bundle exec rake test
