name: CI

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74
        with:
          bundler-cache: true
      - run: bundle exec rubocop
      - run: bundle exec rake test
