name: CI

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ruby/setup-ruby@4c56a21280b36d862b5fc31348f463d60bdc55d5
        with:
          bundler-cache: true
      - run: bundle exec rubocop
      - run: bundle exec rake test
